# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{frameos-builder}
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sergio Rubio"]
  s.date = %q{2010-05-31}
  s.default_executable = %q{frameos-builder}
  s.email = %q{sergio@rubio.name}
  s.executables = ["frameos-builder"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "lib/frameos-builder.rb",
     "lib/rpmdev.rb",
     "resources/boot.msg",
     "resources/comps.xml",
     "resources/frameos-ide.ks",
     "resources/frameos.ks",
     "resources/isolinux.cfg.erb",
     "resources/minpkglist",
     "resources/options.msg",
     "resources/splash.lss",
     "resources/splash.xpm.gz",
     "vendor/cache/choice-0.1.4.gem",
     "vendor/gems/choice-0.1.4/CHANGELOG",
     "vendor/gems/choice-0.1.4/LICENSE",
     "vendor/gems/choice-0.1.4/README",
     "vendor/gems/choice-0.1.4/examples/ftpd.rb",
     "vendor/gems/choice-0.1.4/examples/gamble.rb",
     "vendor/gems/choice-0.1.4/lib/choice.rb",
     "vendor/gems/choice-0.1.4/lib/choice/lazyhash.rb",
     "vendor/gems/choice-0.1.4/lib/choice/option.rb",
     "vendor/gems/choice-0.1.4/lib/choice/parser.rb",
     "vendor/gems/choice-0.1.4/lib/choice/version.rb",
     "vendor/gems/choice-0.1.4/lib/choice/writer.rb",
     "vendor/gems/choice-0.1.4/test/test_choice.rb",
     "vendor/gems/choice-0.1.4/test/test_lazyhash.rb",
     "vendor/gems/choice-0.1.4/test/test_option.rb",
     "vendor/gems/choice-0.1.4/test/test_parser.rb",
     "vendor/gems/choice-0.1.4/test/test_writer.rb",
     "vendor/specifications/choice-0.1.4.gemspec"
  ]
  s.homepage = %q{http://frameos.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{FrameOS ISO image builder}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

