00
 

                       0eInstaller Boot Options07

 -  To disable hardware probing, type: 0blinux noprobe <ENTER>07.  

 -  To test the install media you are using, type: 0blinux mediacheck <ENTER>07.  

 -  To enable rescue mode, type: 0blinux rescue <ENTER>07.  
    Press 0b<F5>07 for more information about rescue mode.

 -  If you have a driver disk, type: 0blinux dd <ENTER>07.

 -  To prompt for the use of other install methods such as network
    install when booting from a CD, type 0blinux askmethod <ENTER>07.

 -  If you have an installer update disk, type: 0blinux updates <ENTER>07.

 -  To test the memory in your system type: 0bmemtest86 <ENTER>07.
    (This option is only available when booting from CD.)

0f[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07
