00
 

                       0eInstaller Boot Options07

 -  To disable hardware probing, type: 9elinux noprobe <ENTER>07.  

 -  To test the install media you are using, type: 9elinux mediacheck <ENTER>07.  

 -  To enable rescue mode, type: 9elinux rescue <ENTER>07.  
    Press 9e<F5>07 for more information about rescue mode.

 -  If you have a driver disk, type: 9elinux dd <ENTER>07.

 -  To prompt for the use of other install methods such as network
    install when booting from a CD, type 9elinux askmethod <ENTER>07.

 -  If you have an installer update disk, type: 9elinux updates <ENTER>07.

 -  To test the memory in your system type: 9ememtest86 <ENTER>07.
    (This option is only available when booting from CD.)

9e[F1-Main] [F2-Options] [F3-General] [F4-Kernel] [F5-Rescue]07
